test

diff --git a/elchemy b/elchemy
--- a/elchemy
+++ b/elchemy
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+version="0.4.40"
+
 function create_file {
     local file=$1
     if [[ ${file} == *"elm-stuff/packages"* ]]; then
@@ -19,19 +21,29 @@ done
 SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
 case "$1" in
+    version)
+        echo "Elchemy $version"
+        ;;
     clean)
       rm -rf ./elm-deps
       rm -rf ./elm-stuff
-    ;;
+      rm -rf ~/.elm-install/github.com/
+      ;;
+    new)
+        mix new $2
+        cd $2
+        $SOURCE_DIR/elchemy init
+        ;;
     init)
         if [ -a ./mix.exs ]
         then
-            mix archive.install https://github.com/wende/elchemy/releases/download/0.4.5/elchemy-0.4.5.ez
+
+            mix archive.install "https://github.com/wende/elchemy/releases/download/$version/elchemy-$version.ez"
             mkdir -p elm
             cp $SOURCE_DIR/templates/elm-package.json ./
             cp $SOURCE_DIR/templates/Hello.elm ./elm/
             cp $SOURCE_DIR/templates/elchemy_test.exs ./test/
-            printf  "Elchemy initialised. Make sure to add:\n\n\tcompilers: [:elchemy, :yecc, :leex, :erlang, :elixir, :app],\n\telixirc_paths: [\"lib\", \"elm-deps\"],\n\telchemy_path: \"elm\",\n\nto your mix.exs file\nThen run mix test to check if everything went fine\n"
+            printf  "Elchemy $version initialised. Make sure to add:\n\n\tcompilers: [:elchemy, :yecc, :leex, :erlang, :elixir, :app],\n\telixirc_paths: [\"lib\", \"elm-deps\"],\n\telchemy_path: \"elm\",\n\nto your mix.exs file\nThen run mix test to check if everything went fine\n"
             printf "\nelm-deps" >> .gitignore
             printf "\nelm-package.json" >> .gitignore
             printf "\nelm-stuff" >> .gitignore
@@ -42,12 +54,14 @@ case "$1" in
     compile)
         rm -rf ".elchemy"
         echo "" > .elchemy_output
-        if ! hash elm-github-install 2>/dev/null; then
-          echo "No elm-github-install found. Installing..."
-          npm i -g elm-github-install
+        if ! [[ $* == *--unsafe* ]]; then
+            if ! hash elm-github-install 2>/dev/null; then
+                echo "No elm-github-install found. Installing..."
+                npm i -g elm-github-install@1.2.0
+            fi
+            elm-install
         fi
-        elm-install
-        for f in `{ find $2/../elm-stuff/packages -name "*.ex" | grep -v "elchemy.ex" ;}`
+        for f in `{ find elm-stuff/packages -name "*.ex" ;}`
         do
           echo "FOUND $f"
           file=$(create_file $f)
@@ -55,17 +69,17 @@ case "$1" in
           cp $f $file
         done
         i=0
-        for f in `{ find $2 -name "*.elm" | grep -v "elm-stuff" | grep -v "#." ; find $2/../elm-stuff/packages -name "*.elm" | grep -v "/tests/" ;}`
+        for f in `{ find $2 -name "*.elm" | grep -v "elm-stuff" | grep -v "#." ; find elm-stuff/packages -name "*.elm" | grep -v "/tests/" ;}`
         do
             if [[ ${f} == *"elm-lang"* ]] || [[ ${f} == *"Elchemy.elm"* ]]; then
                 continue
             fi
             echo "----------"
-            echo "Compiling $f"
+            echo "Type Checking $f"
             echo ">>>>$f" >> .elchemy_output
             # We don't need to typecheck deps again
-            if [[ ${f} != *"elm-stuff"* ]]; then
-                elm-make $f --output .elchemy_output_tmp.js || { echo 'Compilation failed' ; exit 1; }
+            if [[ ${f} != *"elm-stuff"* ]] && ! [[ $* == *--unsafe* ]]; then
+                (echo n | elm-make $f --output .elchemy_output_tmp.js) || { echo 'Type Check failed' ; exit 1; }
                 rm .elchemy_output_tmp.js
             fi
             i=$((i+1))
@@ -73,13 +87,14 @@ case "$1" in
             cat $f >> .elchemy_output
         done
         echo "-- Linking files --"
-        node --max_old_space_size=2048 $SOURCE_DIR/elchemy.js .elchemy_output > .elchemy_elixir_output
+        node --max_old_space_size=8192 $SOURCE_DIR/elchemy.js .elchemy_output .elchemy_elixir_output
         current_file=""
         while IFS= read -r line; do
             if [[ $line =~ ">>>>" ]]; then
                 current_file="${line/\/\///}"
-                current_file="${current_file/>>>>$2/$3}"
+                current_file="${current_file/>>>>/}"
                 echo "Linking: $current_file"
+                current_file="${current_file/$2\//$3/}"
                 current_file="${current_file%%.elm}.elchemy.ex"
                 current_file=$(create_file $current_file)
                 echo "To: $current_file"
